"""empty message

Revision ID: 211e54ac640d
Revises: 758b69b7a603
Create Date: 2023-11-09 15:26:27.019036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '211e54ac640d'
down_revision = '758b69b7a603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dot_thau', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_dot_thau_active')
        batch_op.create_index(batch_op.f('ix_dot_thau_end'), ['end'], unique=False)
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dot_thau', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_dot_thau_end'))
        batch_op.create_index('ix_dot_thau_active', ['active'], unique=False)
        batch_op.drop_column('end')

    # ### end Alembic commands ###
