"""empty message

Revision ID: 758b69b7a603
Revises: 91c5ef58129d
Create Date: 2023-11-09 09:30:53.127290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758b69b7a603'
down_revision = '91c5ef58129d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dot_thau', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_dot_thau_active'), ['active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dot_thau', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dot_thau_active'))
        batch_op.drop_column('active')

    # ### end Alembic commands ###
