"""empty message

Revision ID: 8c2df8c24c2b
Revises: ab47e0035afa
Create Date: 2023-11-02 19:43:53.585184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c2df8c24c2b'
down_revision = 'ab47e0035afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_history_nxt', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_index('ix_import_history_nxt_month')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_history_nxt', schema=None) as batch_op:
        batch_op.create_index('ix_import_history_nxt_month', ['month'], unique=False)
        batch_op.alter_column('month',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
