"""empty message

Revision ID: 91c5ef58129d
Revises: 8c2df8c24c2b
Create Date: 2023-11-06 10:07:01.291859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c5ef58129d'
down_revision = '8c2df8c24c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kho_chan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dot_thau_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dot_thau', ['dot_thau_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kho_chan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dot_thau_id')

    # ### end Alembic commands ###
