"""empty message

Revision ID: ab47e0035afa
Revises: 97b7946aefab
Create Date: 2023-10-30 15:32:27.715885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab47e0035afa'
down_revision = '97b7946aefab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dot_thau', schema=None) as batch_op:
        batch_op.drop_index('ix_dot_thau_code')
        batch_op.create_index(batch_op.f('ix_dot_thau_code'), ['code'], unique=False)

    with op.batch_alter_table('nxt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dot_thau_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dot_thau', ['dot_thau_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_password_hash')
        batch_op.create_index(batch_op.f('ix_user_password_hash'), ['password_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password_hash'))
        batch_op.create_index('ix_user_password_hash', ['password_hash'], unique=False)

    with op.batch_alter_table('nxt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dot_thau_id')

    with op.batch_alter_table('dot_thau', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dot_thau_code'))
        batch_op.create_index('ix_dot_thau_code', ['code'], unique=False)

    # ### end Alembic commands ###
