"""empty message

Revision ID: c20ff5a724d4
Revises: ddf4d737232e
Create Date: 2023-10-28 00:57:22.445704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c20ff5a724d4'
down_revision = 'ddf4d737232e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoat_chat', schema=None) as batch_op:
        batch_op.drop_index('ix_hoat_chat_codeBV')
        batch_op.drop_column('codeBV')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoat_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codeBV', mysql.VARCHAR(length=10), nullable=True))
        batch_op.create_index('ix_hoat_chat_codeBV', ['codeBV'], unique=False)

    # ### end Alembic commands ###
