"""empty message

Revision ID: dc53418077c3
Revises: c20ff5a724d4
Create Date: 2023-10-28 18:44:21.016391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc53418077c3'
down_revision = 'c20ff5a724d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_history', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index('ix_import_history_code')
        batch_op.create_foreign_key(None, 'dot_thau', ['code'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_import_history_code', ['code'], unique=False)
        batch_op.alter_column('code',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
