"""empty message

Revision ID: ddf4d737232e
Revises: 
Create Date: 2023-10-27 23:39:17.586357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf4d737232e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hoat_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codeBV', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_hoat_chat_codeBV'), ['codeBV'], unique=False)

    with op.batch_alter_table('nhom_hoa_duoc_bv', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'hospital', ['hospital_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('set_roles', schema=None) as batch_op:
        batch_op.drop_constraint('set_roles_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('thuoc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codeBV', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_thuoc_codeBV'), ['codeBV'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thuoc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thuoc_codeBV'))
        batch_op.drop_column('codeBV')

    with op.batch_alter_table('set_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('set_roles_ibfk_2', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('nhom_hoa_duoc_bv', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hoat_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hoat_chat_codeBV'))
        batch_op.drop_column('codeBV')

    # ### end Alembic commands ###
